/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/hooks/**/*.{js,jsx,ts,tsx}",
    "./src/data/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
    },
    extend: {
      colors: {
        brand: {
          yellow: "#F5B800",
          cyan: "#00A8CC",
          teal: "#179CBD",
          slate: "#526E87",
          bg: "#efefee",
          red: "#ff3b4d",
          line: "#dfe4e6",
          panel: "#e2e4e6",
          soft: "#e5e5e5",
          "text-dark": "#111827",
          "text-muted": "#4a5568",
          "body-muted": "#55606a",
          "subtle-muted": "#676d75",
        },
        social: {
          whatsapp: "#25D366",
        },
        google: {
          blue: "#4285F4",
          red: "#EA4335",
          yellow: "#FBBC05",
          green: "#34A853",
        },
      },
      fontFamily: {
        sans: ['"Inter"', "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["2.2rem", { lineHeight: "0.96", letterSpacing: "-0.07em" }],
        "display-hero-sm": ["2.8rem", { lineHeight: "0.96", letterSpacing: "-0.07em" }],
        "display-hero-md": ["3.2rem", { lineHeight: "0.96", letterSpacing: "-0.07em" }],
        "display-hero-lg": ["3.7rem", { lineHeight: "0.96", letterSpacing: "-0.07em" }],
        "display-hero-2xl": ["2.5rem", { lineHeight: "0.96", letterSpacing: "-0.07em" }],
        "display-section": ["clamp(2.5rem, 5vw, 5.5rem)", { lineHeight: "1.02", letterSpacing: "-0.05em" }],
        "display-compact": ["clamp(2.5rem, 5vw, 5.2rem)", { lineHeight: "0.95", letterSpacing: "-0.06em" }],
        "display-banner": ["clamp(2.9rem, 4.6vw, 5.2rem)", { lineHeight: "0.9", letterSpacing: "-0.06em" }],
        "section-kicker": ["clamp(1.45rem, 2vw, 2.6rem)", { lineHeight: "1.02", letterSpacing: "-0.07em" }],
        "section-accent": ["clamp(1.35rem, 1.7vw, 1.9rem)", { lineHeight: "1.1", letterSpacing: "-0.06em" }],
        "body-copy": ["1.04rem", { lineHeight: "1.7", letterSpacing: "-0.02em" }],
        "micro-note": ["0.78rem", { lineHeight: "1.2", letterSpacing: "-0.03em" }],
        "team-badge": ["0.7rem", { lineHeight: "0.9", letterSpacing: "0" }],
        "team-badge-sm": ["0.78rem", { lineHeight: "0.9", letterSpacing: "0" }],
        "micro-note-lg": ["0.88rem", { lineHeight: "1.2", letterSpacing: "-0.03em" }],
        "photo-menu": ["1.4rem", { lineHeight: "1.1", letterSpacing: "-0.04em" }],
        "photo-menu-sm": ["1.65rem", { lineHeight: "1.1", letterSpacing: "-0.04em" }],
        "photo-menu-md": ["2rem", { lineHeight: "1.1", letterSpacing: "-0.04em" }],
      },
      maxWidth: {
        "layout-shell": "1280px",
        "header-shell": "720px",
        "header-shell-sm": "780px",
        "header-shell-lg": "900px",
        "header-shell-2xl": "980px",
        "copy-narrow": "480px",
        "copy-medium": "520px",
        "copy-video": "560px",
        "content-cta": "750px",
      },
      boxShadow: {
        nav: "0px 4px 16px rgba(0,0,0,0.10)",
        logo: "0px 4px 4px rgba(0,0,0,0.25)",
        talk: "3px 3px 3px #526E87",
      },
    },
  },
  plugins: [],
};
